name: ${project.artifactId}
version: ${project.version}
author: OhBlihv
website: http://www.spigotmc.org/resources/blivtrails.4544/
main: ${project.groupId}.${project.artifactId}.${project.artifactId}
description: Fancy trails for Fancy people
softdepend: [VanishNoPacket, Essentials, SuperVanish, PremiumVanish]
commands:
    ${project.artifactId}:
        description: Open the Trails menu
        aliases: [trail, trails, btrail, btrails]